services:
  - type: web
    name: amorti
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: node sunucu.js
    envVars:
      - key: NODE_ENV
        value: production
